"""Pydantic models for the timetabling domain."""

from app.models.school import (
    Assignment,
    CurrentAssignment,
    Lesson,
    MoveCheckRequest,
    MoveCheckResponse,
    MoveLessonRequest,
    MoveLessonResponse,
    Room,
    RoomInfo,
    RoomType,
    SlotConflict,
    SlotValidation,
    StudentGroup,
    Subject,
    SubjectRoomRequirement,
    Teacher,
    TeacherAvailability,
    TimeSlot,
    TimetableInput,
    TimetableOutput,
)

__all__ = [
    "Assignment",
    "CurrentAssignment",
    "Lesson",
    "MoveCheckRequest",
    "MoveCheckResponse",
    "MoveLessonRequest",
    "MoveLessonResponse",
    "Room",
    "RoomInfo",
    "RoomType",
    "SlotConflict",
    "SlotValidation",
    "StudentGroup",
    "Subject",
    "SubjectRoomRequirement",
    "Teacher",
    "TeacherAvailability",
    "TimeSlot",
    "TimetableInput",
    "TimetableOutput",
]
